import {
  Calendar,
  Code2,
  Hash,
  Palette,
  Scale,
  Thermometer,
  KeyRound,
  Timer,
  ListTodo,
  Quote,
  IdCard,
  Tag,
  Receipt,
  Brain,
  MessageCircleQuestion,
  Mail,
  PawPrint,
} from 'lucide-react'

export const PROJECT_ICONS = {
  calendar: Calendar,
  hash: Hash,
  palette: Palette,
  scale: Scale,
  thermometer: Thermometer,
  'key-round': KeyRound,
  timer: Timer,
  'list-todo': ListTodo,
  quote: Quote,
  'id-card': IdCard,
  tag: Tag,
  receipt: Receipt,
  brain: Brain,
  'message-circle-question': MessageCircleQuestion,
  mail: Mail,
  'paw-print': PawPrint,
  default: Code2,
}
