import {
  Calendar,
  Code2,
  Hash,
  Palette,
  Scale,
  Thermometer,
  KeyRound,
  Timer,
  ListTodo,
  Quote,
  IdCard,
  Tag,
  Receipt,
  Brain,
  MessageCircleQuestion,
  Mail,
  PawPrint,
  Target,
  Smile,
  Wallet,
  ClipboardCheck,
  GraduationCap,
  Users,
  Truck,
  MessageCircle,
  LogIn,
} from 'lucide-react'

export const PROJECT_ICONS = {
  calendar: Calendar,
  hash: Hash,
  palette: Palette,
  scale: Scale,
  thermometer: Thermometer,
  'key-round': KeyRound,
  timer: Timer,
  'list-todo': ListTodo,
  quote: Quote,
  'id-card': IdCard,
  tag: Tag,
  receipt: Receipt,
  brain: Brain,
  'message-circle-question': MessageCircleQuestion,
  mail: Mail,
  'paw-print': PawPrint,
  target: Target,
  smile: Smile,
  wallet: Wallet,
  'clipboard-check': ClipboardCheck,
  'graduation-cap': GraduationCap,
  users: Users,
  truck: Truck,
  'message-circle': MessageCircle,
  'log-in': LogIn,
  default: Code2,
}
